# Generated by Django 5.0.8 on 2024-08-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='cirurgias_realizadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='conduta_terapeutica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exame_fisico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exames_solicitados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hipoteses_diagnosticas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia_doenca_atual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia_familia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia_fisiologica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia_patologica_pregressa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia_social',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medicamentos_prescritos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medicamentos_suplementos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='observacoes_adicionais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='queixa_principal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='resultado_exames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='duracao',
            field=models.CharField(max_length=20),
        ),
    ]
